[build]
    command = "pnpm install && pnpm build"

[build.processing.html]
    pretty_urls = true

[build.environment]
    NETLIFY_USE_PNPM_APPROVE_BUILDS = "false"
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
