[build]
    command = "pnpm approve-builds puppeteer && pnpm install && pnpm build"

[build.processing.html]
    pretty_urls = true

[build.environment]
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
